-- auto-generated definition
create table bookings
(
    id                     int unsigned auto_increment
        primary key,
    restaurant_id          int unsigned                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        not null,
    customer_id            int unsigned                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        not null,
    name                   varchar(255)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        not null,
    mobile                 varchar(255)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        not null,
    email                  varchar(255)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        not null,
    pax                    int unsigned                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        not null,
    children               int unsigned    default '0'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         not null,
    date                   date                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                not null,
    time                   time                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                not null,
    is_special             tinyint(1)      default 0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           not null,
    deal_id                int unsigned                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        null,
    deal                   varchar(255)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        not null,
    deal_conditions        text                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                null,
    deal_bucket_id         int unsigned                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        null,
    price                  double(8, 2)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        null,
    cover_charge           tinyint(1)      default 0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           not null,
    privilege              varchar(255)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        null,
    privilege_id           int unsigned                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        null,
    medium                 enum ('android', 'ios', 'web', 'concierge', 'google', 'api_partner', 'booking_widget', 'msite', 'desktop')                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          not null,
    state                  enum ('pending', 'confirmed', 'complete', 'cancelled')                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              not null,
    state_status           enum ('waitlist', 'priority waitlisted', 'processing', 'confirmed', 'on-hold', 'no show', 'denied', 'cancelled', 'checked in', 'materialized', 'complete', 'reverse_waitlist', 'rescheduled')                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       not null,
    attended               tinyint(1)      default 0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           not null,
    materialized_with      varchar(255)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        null,
    origin_source          enum ('lead', 'waitlist', 'confirmed', 'freecheers')                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                not null,
    completion_source      enum ('concierge', 'checkin', 'auto-mailer', 'livetable', 'customer', 'auto-sms', 'shawman', 'ivr', 'bbq-api', 'api_partner', 'bulk_operation', 'pos_api_partner')                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  null,
    no_payment             tinyint(1)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          null,
    cancel_reason          enum ('restaurant closed', 'plan cancelled', 'sold out', 'waiting', 'duplicate', 'test booking', 'change of plans', 'booking done by mistake', 'wrong restaurant', 'closed permanently', 'closed temporarily due to lockdown', 'overbooked and not accepting further reservations', 'overbooked on this festive day', 'closed temporarily', 'auto_cancelled_concurrent', 'customer did not go', 'booking is waitlisted', 'booked a wrong restaurant', 'found a better offer elsewhere', 'booked by mistake', 'restaurant declined booking', 'found a confirmed booking elsewhere', 'forgot to go', 'restaurant was too far', 'went to a different restaurant instead', 'reached but didn''t get a table', 'others') null,
    customer_remarks       varchar(255)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        null,
    notes                  varchar(255)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        null,
    remark                 varchar(255)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        null,
    bill_amount            double(8, 2)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        null,
    bill_excluding_tax     double(8, 2)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        null comment 'amount of bill excluding tax',
    bill_number            varchar(255)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        null,
    table_number           varchar(255)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        null,
    no_points              tinyint(1)      default 0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           not null,
    shawman_booking_id     int                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 null,
    shawman_booking_status enum ('Confirmed', 'Cancelled')                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     null,
    partner                varchar(255)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        null,
    partner_booking_id     varchar(255)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        null,
    created_at             timestamp       default CURRENT_TIMESTAMP                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           not null,
    updated_at             timestamp       default CURRENT_TIMESTAMP                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           not null on update CURRENT_TIMESTAMP,
    bill_declined_message  text                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                null,
    bill_status            enum ('not uploaded', 'uploaded', 'declined', 'accepted', 'customer_declined')                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      not null,
    eazypay_declined       enum ('0', '1') default '0'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         not null,
    bill_declined_reason   enum ('Restaurant Name in Booking not matching with Bill', 'Date/Time of Booking Not Matching with Bill', 'Bill Not Clear/Not Readable', 'Discount on Bill Not matching with EazyDiner deal', 'Invalid Bill')                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       null,
    lat_long               varchar(255)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        not null,
    constraint bookings_customer_id_foreign
        foreign key (customer_id) references customers (id)
            on update cascade,
    constraint bookings_deal_bucket_id_foreign
        foreign key (deal_bucket_id) references deal_buckets (id)
            on update cascade,
    constraint bookings_deal_id_foreign
        foreign key (deal_id) references deals (id)
            on update cascade on delete cascade,
    constraint bookings_privilege_id_foreign
        foreign key (privilege_id) references badges (id)
            on update cascade,
    constraint bookings_restaurant_id_foreign
        foreign key (restaurant_id) references restaurants (id)
            on update cascade
)
    collate = utf8mb3_unicode_ci;

create index bookings_created_at_idx
    on bookings (created_at);

create index bookings_state_idx
    on bookings (state);

create index date
    on bookings (date);

