-- auto-generated definition
create table locations_data
(
    -- group_id is the smallest area in the map.
    -- location hierarchy
    -- group_id < subarea < area < region < city < state < country
    group_id          int                                   default 0                 not null,
    subarea_id        int                                   default 0                 not null,
    area_id           int                                   default 0                 not null,
    region_id         int                                   default 0                 not null,
    city_id           int                                   default 0                 not null,
    state_id          int unsigned                                                    null,
    country_id        int                                   default 0                 not null,
    id                bigint                                default 0                 not null,
    name              varchar(197)                                                    null,
    type              varchar(7) collate utf8mb4_general_ci default ''                not null,
    code              varchar(55) collate latin1_bin        default ''                not null,
    group_name        varchar(150)                                                    null,
    group_code        varchar(45) collate latin1_bin                                  null,
    group_type        enum ('hotel', 'mall', 'place', 'market')                       null,
    subarea_name      varchar(150)                                                    null,
    subarea_code      varchar(55) collate latin1_bin                                  null,
    area_name         varchar(150)                                                    null,
    area_code         varchar(45) collate latin1_bin                                  null,
    region_name       varchar(45)                                                     null,
    region_code       varchar(45) collate latin1_bin                                  null,
    region_popular    enum ('Yes', 'No')                                              not null,
    city_name         varchar(45)                                                     not null,
    city_code         varchar(45)                           default ''                not null,
    state_name        varchar(100) collate utf8mb3_unicode_ci                         null,
    state_code        varchar(10) collate utf8mb3_unicode_ci                          null,
    timezone          varchar(255)                                                    not null,
    is_popular        tinyint                               default 0                 not null,
    country_name      varchar(100)                                                    null,
    currency          varchar(255)                                                    not null,
    country_code      int                                                             null,
    isd_code          varchar(255)                                                    null,
    std_code          bigint                                                          null,
    group_status      enum ('0', '1')                       default '0'               not null,
    subarea_status    enum ('0', '1')                       default '0'               not null,
    area_status       enum ('1', '0')                       default '1'               not null,
    region_status     enum ('1', '0')                       default '1'               not null,
    city_status       tinyint                               default 0                 not null,
    country_status    tinyint(1)                            default 0                 not null,
    group_latitude    decimal(11, 8)                                                  null,
    group_longitude   decimal(11, 8)                                                  null,
    subarea_latitude  float                                                           null,
    subarea_longitude float                                                           null,
    area_latitude     float                                                           null,
    area_longitude    float                                                           null,
    region_latitude   float                                                           null,
    region_longitude  float                                                           null,
    city_latitude     float                                                           null,
    city_longitude    float                                                           null,
    country_latitude  float                                                           null,
    country_longitude float                                                           null,
    created_at        datetime                              default CURRENT_TIMESTAMP null,
    updated_at        datetime                              default CURRENT_TIMESTAMP null on update CURRENT_TIMESTAMP,
    geofence_data     json                                                            null,
    short_name        varchar(100)                                                    null,
    radius            decimal(10, 2)                                                  null
);

